(setq viper-inhibit-startup-message 't)
(setq viper-expert-level '5)
(define-key viper-vi-global-user-map (kbd "/") 'viper-isearch-forward)
(define-key viper-vi-global-user-map (kbd "?") 'viper-isearch-backward)
(define-key viper-vi-global-user-map (kbd "n") 'isearch-repeat-forward)
(define-key viper-vi-global-user-map (kbd "N") 'isearch-repeat-backward)
(define-key viper-vi-global-user-map (kbd "C-l") 'ido-switch-buffer)
(define-key viper-vi-global-user-map (kbd "SPC") (lambda () (interactive) (scroll-up 18)))
(define-key viper-vi-global-user-map (kbd "q") (lambda () (interactive) (scroll-down 18)))
;;(setq vimpulse-experimental nil)
;;(setq viper-ESC-moves-cursor-back t)
(setq viper-auto-indent t)
;;(setq viper-case-fold-search t)
;;(setq viper-ex-style-editing nil)
;;(setq viper-insert-state-cursor-color "#00cd00")
(setq viper-insert-state-cursor-color "Green")
;;(setq viper-re-search t)
;;(setq viper-want-ctl-h-help t))
;; The following makes sure that in termial mode 
;; the ESC key is instant (with not lag)
(setq viper-translate-all-ESC-keysequences t)
(setq viper-no-multiple-ESC t)	
(setq viper-fast-keyseq-timeout 0)
